
dataset_config:
  dataname: blood
  # image, 图片路径
  dataset: /data/blood_dvm/data/blood/dataset/图像数据/
  # result, 结果保存路径
  image_result_path: /data/blood_dvm/data/result/baseline/image/
  num_cls: 7
  t_sne_path: /data/blood_dvm/data/result/end/t_sne/efficientb1/
  data_dir: /data/blood_dvm/data/blood/


train_config:
  mode: train
  epochs: 275
  max_epochs: 2000   
  # lr_max: 5e-4
  lr_max: 1e-3
  # lr_max: 5e-5           # H2T用这个
  # lr_max: 1e-5
  # lr_max: 5e-6
  # lr_max: 3e-3
  lr_min: 0
  batch_size: 64
  seed: 2024
  # lossfunc: crossentropy
  # lossfunc: ldamloss
  lossfunc: focalloss
  gamma: 0.5
  find_epoch: true
  num_cls: 7
  # checkpoint_path: /data/blood_dvm/data/result/checkpoint_pth/


H2T:
  h2t: false
  rho_h2t: 0.35


model_config:
  # net_v: efficientnet-b0
  # net_v: efficientnet-b2
  net_v: efficientnet-b1

  # net_v: vit16
  # net_v: vit32
  # net_v: vit16_in21k          # 这个是运行的网络的名字, 切换使用不同的网络
  # net_v: vit32_in21k

  # net_v: vit_new
  
  # net_v: shufflenet
  freeze_layers: false



